<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LMU.Telemetry.Core\LMU.Telemetry.Core.csproj" />
    <ProjectReference Include="..\LMU.Analysis.Engine\LMU.Analysis.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\TrackMaps\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\wheel_silhouette.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="**\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>


  <Target Name="CopyDuckDBNative" AfterTargets="Build">
    <Copy SourceFiles="$(OutDir)runtimes\win-x64\native\duckdb.dll" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" Condition="Exists('$(OutDir)runtimes\win-x64\native\duckdb.dll')" />
  </Target>

</Project>
